# Generated by Django 4.2 on 2025-01-14 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, upload_to="image/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="introduction",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
